config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :show] do
    resources :ideas, only:  [:show, :edit, :update, :destroy]
  end

  resources :ideas, only: [:new, :create, :index]
  resources :images, only: [:index, :edit]
  resources :users

  get     '/login',  to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
    resources :images
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :category
  validates :title, presence: true
  validates :notes, presence: true
  belongs_to :user
  has_many :image_ideas
  has_many :images, through: :image_ideas, dependent: :destroy

end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  has_many :image_ideas
  has_many :ideas, through: :image_ideas, dependent: :destroy
end

app/models/image_idea.rb
class ImageIdea < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_confirmation_of :password
  validates :email, presence: :true, uniqueness: true
  validates :name, presence: :true
  has_many :ideas
  enum role: [:default, :admin]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action(:require_admin)

  def require_admin
    render file: 'public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def show
    @user = User.find(session[:user_id]) if !session[:user_id].nil?
    @category = Category.find(params[:id])
    @ideas = @category.ideas
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
    redirect_to  admin_categories_path
    else
    render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.save

    redirect_to admin_images_path
  end

  def edit

  end

  def update
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to admin_images_path
  end

  private

  def image_params
    params.require(:image).permit(:image)
  end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def current_admin?
    current_user && current_user.admin?
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @user = User.find(session[:user_id]) if !session[:user_id].nil?
    @category = Category.find(params[:id])
    @ideas = @category.ideas
    @users_ideas = @user.ideas.where(category_id: @category.id) if !session[:user_id].nil?
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def new
    @idea = Idea.new
    @categories = Category.all
    @images = Image.all
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user_id = session[:user_id]
    if @idea.save
      redirect_to category_path(@idea.category)
    else
      redirect_to new_idea_path
    end
  end

  def show
    @idea = Idea.find(params[:id])
    @image = Image.new
  end

  def edit
    @images = Image.all

    @idea = Idea.find(params[:id])
    @categories = Category.all
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to category_idea_path(@idea.category, @idea)
    else
      redirect_to edit_idea_path
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to category_path(@idea.category)
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :notes, :category_id, :user_id, image_ids: [] )
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end


  private

  def image_params
    params.require(:image).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.nil?
      flash[:danger] = "User does not exist. Create one below"
      redirect_to login_path
    elsif @user.authenticate(params[:password]) && @user.admin?
      flash[:success] = "You Successfully Logged in!"
      session[:user_id] = @user.id
      redirect_to admin_categories_path
    elsif @user.authenticate(params[:password])
      flash[:success] = "You Successfully Logged in!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:fail] = "Email and password don't match"
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "You Successfully Logged out!"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have successfully created a user"
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user)
  end 

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<div class="container-fluid">
<div class="new_category">
<%= form_for [:admin, @category] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit class: "btn btn-default btn-sm"%>
<% end %>
</div>
</div>

app/views/admin/categories/edit.html.erb
<center><h1> Edit Category </h1><center>
<%= render partial: "form" %>

app/views/admin/categories/index.html.erb
<div class="container">
  <h1> List of Categories </h1>
  <p><%= link_to "Create New Category", new_admin_category_path %></p>
  <ol>
  <% @categories.each do |category| %></br>
  <li><%= link_to category.name, category_path(category) %></li>
  <%= link_to "Edit", edit_admin_category_path(category) %></br>
    <%= link_to "Delete", admin_category_path(category), method: :delete %></br>
<% end %>
</ol>
</div>

app/views/admin/categories/new.html.erb
<center><h1> Create a New Category </h1><center>
<%= render partial: "form" %>

app/views/admin/images/index.html.erb
<div class="container-fluid">
<p><%= link_to "Add a New Image", new_admin_image_path %><p>
<% @images.each do |image| %>
<%= image_tag image.image.url, :width => '25%' %>
<%= link_to "Delete", admin_image_path(image), method: :delete %>
<% end %>
</div>

app/views/admin/images/new.html.erb
<%= form_for([:admin, @image], html: {multipart: true}) do |f| %>
<%= f.label  "Attach an Image" %><br/>
<%= f.file_field :image %>
<%= f.submit "Upload Image", class: 'btn btn-default btn-sm'%>
<% end %>

app/views/categories/_form.html.erb
<div class="container-fluid">
<div class="new_category">
<%= form_for @category do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit class: "btn btn-default btn-sm"%>
<% end %>
</div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1> List of Categories </h1>
  <ol>
  <% @categories.each do |category| %></br>
  <li><h3><%= link_to category.name, category_path(category) %></h3></li>

<% end %>
</ol>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-sm-3">
<center<p>Category Name:<%= @category.name %></p>

<p><strong> List of <%= @category.name %> Ideas </strong> </p>
<% if @user == nil %>
<p> <p>
  <% else %>
  <ol>
<% @users_ideas.each do |idea| %>

<li><%= link_to idea.title, category_idea_path(@category, idea) %></li>
<%= link_to "Edit", edit_category_idea_path(@category, idea) %>
<%= link_to "Delete", category_idea_path(@category, idea), method: :delete %>

<% end %>
<ol>
<% end %>

</ol>
</div>
</div>
</div>

app/views/ideas/_form.html.erb
<div class="container-fluid">
    <div class="idea_form">
        <%= form_for [@idea.category, @idea] do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :notes %>
        <%= f.text_field :notes %>
        <%= f.collection_select :category_id, @categories,:id,:name, include_black: true %>
        <%= f.submit class: 'btn btn-default btn-sm' %>
      </div>
    </br>
      <div>
        <% @images.each do |image| %>
        <center><p>  <%= check_box_tag(:image_id, image.id, false, name: "idea[image_ids][]", id: "image-#{image.id}", include_blank: true) %>
          <%= image_tag image.image.url, :width => '25%' %></p></cetner>
        <%end %>
      </div>
    <% end %>
</div>

app/views/ideas/edit.html.erb
<center><h1> Edit your category </h1><center>
<%= render partial: "form" %>

app/views/ideas/new.html.erb
<div class="idea">
<h1> Create a New Idea </h1>
</div>
<%= render partial: "form" %>

app/views/ideas/show.html.erb
<div class="container">
<p><%= link_to @idea.category.name, category_path(@idea.category) %><p>

<p><strong>Idea Name:</strong> <%= @idea.title %></p>
<p><strong>Idea Content:</strong> <%= @idea.notes %></p>


</br>
</br>
</br>

<div>
  <div class="row">
<% @idea.images.each do |image| %>
<div class="col-md-4"><%= image_tag image.image.url, :width => '55%' %></div>
<% end %>
</div>
</div>

</div>

app/views/images/index.html.erb
<div class="container-fluid">

<% @images.each do |image| %>
<%= image_tag image.image.url, :width => '25%' %>
<% end %>
</div>

app/views/images/new.html.erb
<%= form_for(@image, html: {multipart: true}) do |f| %>
<%= f.label  "Attach an Image" %><br/>
<%= f.file_field :image %>
<%= f.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="abc">

<p>IdeaBox</p>


</div>
        <!-- /#sidebar-wrapper -->
    <div id="wrapper">
    <div class="overlay"></div>
    <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
            </li>

            <li>
                <a <%= link_to "Categories",categories_path  %></a>
            </li>
            <li>
                <a <%= link_to "All Images", images_path%></a>
            </li>
            <li>
              <a <%= link_to "New Idea", new_idea_path %></a>
            </li>
            <li>
              <a href="/users/new">Create a New User</a>
            </li>
            <li>
              <% if session[:user_id].nil? %>
              <% "not logged in" %>
              <% else %>
              <a <%= link_to "Account Details", user_path(User.find(session[:user_id]))%></a>
              <% end %>
            </li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Dropdown heading</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
            <li>
              <% if logged_in? %>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Login", login_path %></li>
              <% end %>
            </li>
        </ul>
    </nav>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
            <span class="hamb-top"></span>
      <span class="hamb-middle"></span>
    <span class="hamb-bottom"></span>
        </button>

            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideabox</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <% flash.each do |key, value| %>
    <div class= "alert alert-<%= key %> alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>

    <center><%= value %><center>
    <% end %>
  </div>
    <%= yield %>



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<center><div class="container">
<h1> Edit User </h1>
<%= form_for @user do |f| %>
<%= f.label :name %></br>
<%= f.text_field :name %></br>
<%= f.label :email  %></br>
<%= f.text_field :email %></br>
<%= f.label :password %><br>
<%= f.password_field :password %></br>
<%= f.label :password_confirmation %></br>
<%= f.password_field :password_confirmation %></br>
<%= f.submit class: 'btn btn-default'%>
<% end %>
</div></center>

app/views/users/new.html.erb
<div class="container">
<center><h1> Create a New User </h1></center>
<%= form_for @user do |f| %>
<%= f.label :name %></br>
<%= f.text_field :name %></br>
<%= f.label :email  %></br>
<%= f.text_field :email %></br>
<%= f.label :password %><br>
<%= f.password_field :password %></br>
<%= f.label :password_confirmation %></br>
<%= f.password_field :password_confirmation %></br>
<%= f.submit class: 'btn btn-default'%>
<% end %>
</div>

app/views/users/show.html.erb
<center><h1>Welcome <%= @user.name %>!</h1><center>
<%= link_to "Edit Account", edit_user_path(@user) %>